### ISSUE TITLE
Show e-mail field for a logged in user on an offer apply form?

### ISSUE THREAD

**Issue by Yog** [stxnext-csr/volontulo#253]
We have few options:
- don't show the e-mail field
- show it, but uneditable
- show it with an option to edit for a different email

**Comment by Yog** [comment]
Consulting with Dominik the outcome is to:
- show it, but uneditable

**Comment by doslizlo** [comment]
_If user is logged in:_ let's not give him an option to edit the email address, but let's show it just for user to know what address the emails will be sent to. It is most expected to use  the email address assigned to account. As facebook login is also considered in the future, s/he should have an option to see it. though.

_If user not logged in:_ we should ask him/her to log in and give possibility to participate in action without logging in, just with entering email address. Then:
- if this email address turns out to be assigned to a registered account - user should get the proper alert. 
- if this email address is not assigned to a registered account - user should be able to sign up for an offer; in emails s/he gets s/he should also be given a link to activate full account for this email address.
